# Clone version node
FROM node:16.18-alpine

# Directory app run
WORKDIR /usr/local/app/nuxt

# Copy package to docker
COPY ["package*.json", "./"]

# Install package
RUN npm install --silent

# Copy package to docker
COPY . .

# Run build
RUN npm run build

# Run generate
RUN npm run generate

# Server host local
ENV HOST 0.0.0.0
